# Regenerates docs/sw-precache.js: the list of files the service worker caches + the CACHE VERSION.
#   powershell -ExecutionPolicy Bypass -File docs\tools\build-precache.ps1            (bumps the version by 1)
#   powershell -ExecutionPolicy Bypass -File docs\tools\build-precache.ps1 -Version 7  (sets it)
# Run it every time you change any game file, then publish. Players get the update on their next launch.
param([int]$Version = 0)

$docs = Split-Path -Parent $PSScriptRoot
$out = Join-Path $docs 'sw-precache.js'

if ($Version -le 0) {
  $Version = 1
  if (Test-Path $out) {
    $m = [regex]::Match((Get-Content $out -Raw), 'CACHE_VERSION\s*=\s*(\d+)')
    if ($m.Success) { $Version = [int]$m.Groups[1].Value + 1 }
  }
}

$exclude = @('sw.js', 'sw-precache.js', 'serve.ps1', 'PORT_NOTES.md')
$files = Get-ChildItem -Path $docs -Recurse -File |
  Where-Object {
    $rel = $_.FullName.Substring($docs.Length + 1).Replace('\', '/')
    -not ($rel -like 'tools/*') -and ($exclude -notcontains $rel) -and ($_.Extension -ne '.md')
  } |
  ForEach-Object { './' + $_.FullName.Substring($docs.Length + 1).Replace('\', '/') } |
  Sort-Object

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// GENERATED by tools/build-precache.ps1 - do not edit by hand.')
[void]$sb.AppendLine("self.CACHE_VERSION = $Version;")
[void]$sb.AppendLine("self.PHASER_URL = 'https://cdnjs.cloudflare.com/ajax/libs/phaser/3.80.1/phaser.min.js';")
[void]$sb.AppendLine('self.PRECACHE_URLS = [')
[void]$sb.AppendLine("  './',")
foreach ($f in $files) { [void]$sb.AppendLine("  '$f',") }
[void]$sb.AppendLine('];')
[IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "sw-precache.js: version $Version, $($files.Count) files" -ForegroundColor Green
